export default {
  KEYCLOAK_REALM: process.env.REACT_APP_KEYCLOAK_REALM,
  KEYCLOAK_URL: process.env.REACT_APP_KEYCLOAK_URL,
  KEYCLOAK_CLIENT_ID: process.env.REACT_APP_KEYCLOAK_CLIENT_ID,
  BACKEND: process.env.REACT_APP_BACKEND
};
